version: '3.8'

services:
  app:
    build: .
    container_name: app-survey
    volumes:
      - .:/var/www
      - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - network-survey

  nginx:
    build: .docker/nginx
    container_name: nginx-survey
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - network-survey

  db:
    build: ./.docker/mysql
    container_name: db-survey
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=survey
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - network-survey

networks:
  network-survey:
    driver: bridge